In [37]:
import pandas as pd

df = pd.read_excel("Book2.xlsx")
df

,Acetaldehyde,อะเซทัลดีไฮด์,Ethanal,Aldehyde,Acetaldehyde,Ethyl aldehyde,Acetic aldehyde,Unnamed: 7,Unnamed: 8
0,Acetic acid,กรดน้ำส้ม,กรดแอซีติก,กรดอะซิติก,ethanoic acid,ethylic acid,methanecarboxylic acid,vinegar acid,glacial acetic acid
1,Acetylene,Narcylen,Ethyne,Vinylene,ACETYLENE,Ethine,Acetylen,ก๊าซอะเซทิลีน,แก๊สอะเซทิลีน
2,Acrylic acid,Acroleic acid,2-Propenoic acid,Propene acid,Propenoic acid,NaN,NaN,NaN,NaN
3,Acrylonitrile Butadiene Styrene (ABS),ABS,พลาสติก ABS,อะคริโลไนไตรล์ บิวทาไดอีน สไตรีน,NaN,NaN,NaN,NaN,NaN
4,Alachlor,อะลาคลอร์,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...
1920,อีแอล-โปร,อีแอล-โปร,EL-Pro,EL-Pro (brand),NaN,NaN,NaN,NaN,NaN
1921,อีแอล-ลีน,อีแอล-ลีน,EL-Lean,EL-Lean (brand),NaN,NaN,NaN,NaN,NaN
1922,อีโคสเฟียร์,อีโคสเฟียร์,Ecosphere,Ecosphere (product),NaN,NaN,NaN,NaN,NaN
1923,อุปกรณ์ที่ใช้สำหรับการแยกวงจรภายใต้สภาวะโหลด,เบรกเกอร์,Circuit breaker (under load),load break switch,NaN,NaN,NaN,NaN,NaN
1924,อุปกรณ์ประปา,อุปกรณ์สุขภัณฑ์,Plumbing fixtures,water supply equipment,NaN,NaN,NaN,NaN,NaN

In [7]:
df.to_csv("Book.csv",encoding='utf-8-sig',index=False)

In [56]:
new = pd.read_csv("Book.csv")
long_list = new.values.flatten().tolist()
dup = dict()
word_dup = list()
for word in long_list:
    if pd.notna(word) and isinstance(word, str):  # เช็คว่าไม่ใช่ NaN และเป็น string
        use = str(word.strip())
        if use not in dup:
            dup[use] = 1
        else:
            dup[use] += 1
            word_dup.append(use)
test = set(word_dup)

In [53]:
test = set(word_dup)
test

{'1-บิวทีน',
 '100% Jasmine Rice',
 'AAC block',
 'Acid',
 'Acrylic sheet',
 'Aluminium tin',
 'Aluminum can',
 'Aluminum can with lid',
 'Aluminum cans and lids',
 'Aluminum packaging',
 'Automotive Part',
 'BPA',
 'Bag / Pouch',
 'Bag with floral embossed pattern',
 'Bagged',
 'Beverage',
 'Beverage can',
 'Biodiesel of fatty acid methyl ester type',
 'Bisphenol A',
 'Block rubber',
 'Bottled Coca-Cola',
 'Brand',
 'Brick',
 'Brown Jasmine Rice',
 'Brown liner paper for boxes',
 'Building Material',
 'Bulk toilet paper',
 'Butene-1',
 'CX',
 'Calcium carbonate',
 'Calendar bag / Calendar holder bag',
 'Calendar pouch',
 'Canned pineapple slices in clear syrup',
 'Canned sweet corn',
 'Caramel coated sugar',
 'Carbonless continuous form',
 'Carpet tile',
 'Cement floor tile',
 'Cement roof tile',
 'Ceramic roof tile',
 'Ceramic roof tile and ridge cap',
 'Ceramic roofing system',
 'Ceramic tile',
 'Chang Classic Beer',
 'Chang beer',
 'Chemical',
 'Chemical acid',
 'Chicken',
 'Chipboard',
 'Chocolate marble cake',
 'Chocolate milk ice cream',
 'Circle bag',
 'Clay roof tile',
 'Cleaned fresh duck',
 'Coated drafting paper',
 'Coated engineering paper',
 'Coated white cardboard',
 'Coca-Cola',
 'Coffee almond ice cream',
 'Coke',
 'Coke bottle',
 'Concrete roof tile',
 'Concrete tile',
 'Conditioned nitric acid',
 'Continuous chemical paper without lines',
 'Continuous paper / Continuous form',
 'Continuous paper without lines',
 'Cookies and cream ice cream',
 'Corn kernels',
 'Corrugating medium paper (grade)',
 'Corrugating medium paper (weight)',
 'Cracker Bottom',
 'Crescent woven bag',
 'Crystal brand water',
 'Crystal drinking water',
 'Curry puff-shaped water hyacinth bag',
 'Custom license plate frame',
 'Dairy ice cream',
 'Decorative flooring',
 'Deformed steel bar',
 'Dot matrix paper',
 'Drafting paper / Blueprint paper',
 'Dried rice noodles',
 'Drink can',
 'Eco-friendly photo frame',
 'Elephant dung paper',
 'Elephant dung paper photo frame',
 'Elephant poop paper',
 'Embedded Aluminum Stair Nosing',
 'Embossed flower bag',
 'Engineering paper',
 'Est drink',
 'Est soft drink',
 'Ethanol',
 'Ethene',
 'Ethnic woven handbag',
 'Ethylene',
 'Ethylene oxide',
 'FAME biodiesel',
 'Fiber cement roof tile',
 'Fibre cement roofing',
 'Flat concrete roof tile',
 'Floor carpet',
 'Floor tile',
 'Flooring tile',
 'Floral woven square bag',
 'Fluting paper',
 'Food Brand',
 'Fresh dairy ice cream',
 'Fresh milk ice cream',
 'Front grille and front bumper for Mazda cars',
 'Full-fat dehulled soybean',
 'Galvanized steel pipe',
 'Galvanized steel sheet',
 'Glass santol / Candied santol',
 'Glazed porcelain tile',
 'Glued rubberwood',
 'Golden liner board',
 'Golden yellow liner paper for boxes',
 'Golden yellow liner paper for boxes (weight)',
 'Grain',
 'Green tea milk ice cream',
 'Gypsum backing paper',
 'Gypsum facing paper',
 'H2',
 'HA latex',
 'HDPE pellets',
 'HR steel sheet',
 'Heat insulating glass / Insulated glass',
 'High ammonia concentrated latex',
 'High performance fluting',
 'High strength corrugating medium paper',
 'High strength corrugating medium paper (weight)',
 'High-Pong',
 'High-density polyethylene plastic pellets',
 'Hollow core precast concrete floor slab',
 'Hollow core slab',
 'Home & Building Materials',
 'Hot rolled steel sheet',
 'Hydol',
 'Hydrogen',
 'Hydrolysed',
 'Hydrolyzed',
 'Hydrowax',
 'Hyper-Low',
 'Industrial Chemical',
 'Industrial Material',
 'Industrial paper wipes',
 'Industrial roll paper towel',
 'Industrial stretch kraft',
 'Instant noodles',
 'Japanese green tea',
 'Jasmine Rice',
 'Jumbo roll toilet paper',
 'K2CO3',
 'Karen-style water hyacinth handbag with handle',
 'Kerosene',
 'Kraft liner board',
 'Kraft paper for bag making/packaging',
 'Kratingdaeng / Red Bull (Thai)',
 'LA latex',
 'LLDPE pellets',
 "Lady's water hyacinth compact bag",
 'Laminated kraft paper',
 'Laminated rubberwood (grade)',
 'Laminated safety glass',
 'Latex',
 'Leo beer can',
 'Lidded aluminum can',
 'Light ENP@R',
 'Light brown liner paper for boxes',
 'Light brown liner paper for boxes (grade)',
 'Light kraft liner',
 'Limestone',
 'Linear low-density polyethylene plastic pellets',
 'Live poultry',
 'Low ammonia concentrated latex',
 'Low-E glass',
 'MDF',
 'MEG',
 'MMA',
 'MOP',
 'MTBE (methyl tert-butyl ether)',
 'Mackerel in tomato sauce',
 'Marble chocolate cake',
 'Maximum strength corrugating medium paper',
 'Mazda front end',
 'Milk ice cream',
 'Milk ice cream with Kopiko coffee almond',
 'Milk ice cream with chocolate',
 'Milk ice cream with cookies & cream',
 'Milk ice cream with green tea',
 'Milk ice cream with rum raisin',
 'Milk ice cream with strawberry',
 'Milk ice cream with vanilla flavor',
 'Mini crescent woven bag',
 'Miniature half-circle water hyacinth bag',
 'Mitr Phol brown sugar',
 'Mitr Phol cane sugar',
 'Mitr Phol natural cane sugar',
 'Mixed ENP@R',
 'Mixed Xylene',
 'Moden Glass (sheet)',
 'Modern concrete tile',
 'Modified vanilla ice cream',
 'Monosodium Phosphate',
 'Montania',
 'Mosaic',
 'Mosaic tile',
 'Multi-layer safety glass / Laminated glass',
 'NAMECO',
 'NBMA',
 'Natural',
 'Natural yogurt',
 'Nitric acid',
 'Nitrogen',
 'Non-Aromatics Mixture (CMix)',
 'Nylon 6',
 'OMEPRAZOLE 20 mg',
 'Offset laminated-Die cut-Corrugated Carton',
 'Open dumping of community solid waste',
 'Organic brown rice milk',
 'Orthoxylene',
 'Oval chicken basket',
 'Oval poultry basket',
 'Oval shaped handbag with handle',
 'Oval tote bag',
 'Oxirane',
 'Oxygen',
 'PE',
 'PE Foam',
 'PE pipe',
 'PET PREFORM 600 29/25 Clear 13.5g. Manu.',
 'PET pellets',
 'PO',
 'PP compound',
 'PP pellets',
 'PPR pipe',
 'PTA',
 'PVC resin',
 'Packaged tapioca flour',
 'Packaging Material',
 'Packaging kraft',
 'Palm fatty acid',
 'Palm kernel shell',
 'Palm kernel shell (CO2only)',
 'Palm oil fatty acid',
 'Panang Curry',
 'Pao washing powder',
 'Paper',
 'Paper for back side of gypsum board',
 'Paper for front side of gypsum board',
 'Paper sheet',
 'Paper towels',
 'Paraffin wax',
 'Paraquat',
 'Particleboard',
 'Pasteurized low-fat fresh milk',
 'Perforated industrial kraft',
 'Perforated stretchable kraft paper for industrial bags',
 'PharmaMOP',
 'Phenol',
 'Phosphoric acid',
 'Phthalic anhydride',
 'Pig',
 'Pink',
 'Plain yogurt',
 'Plastic coated kraft paper for bag making /',
 'Plastic coated stretchable kraft paper for industrial bags',
 'Pleated woven bag',
 'Polo Upcycling by GC',
 'Poly-cotton yarn',
 'Polybutadiene',
 'Polycarbonate',
 'Polyester resin',
 'Polyester staple fiber (PSF)',
 'Polyester thread',
 'Polyester yarn',
 'Polyethylene terephthalate (PET)',
 'Polyethylene terephthalate plastic pellets',
 'Polypropylene (PP)',
 'Polypropylene plastic pellets',
 'Polyurethane (flexible polyurethane)',
 'Polyurethane (rigid urethane board)',
 'Porcelain tile',
 'Potassium hydroxide',
 'Precast CAST14',
 'Precision-cut ceramic tile',
 'Precision-cut floor tile',
 'Premium grade golden yellow liner paper for boxes',
 'Premium grade golden yellow liner paper for boxes (weight)',
 'Premium grade white liner paper for boxes',
 'Premium white liner',
 'Premjit square water hyacinth bag',
 'Preservative (Benzaldehyde)',
 'Preservative (Bisphenol A)',
 'Preservative (Wood preservative)',
 'Preserve',
 'Printed pattern car license plate frame',
 'Propene',
 'Propylene',
 'Propylene Oxide (PO)',
 'Pure coconut oil',
 'Purified Terephthalic Acid : PTA',
 'Purified terephthalic acid',
 'Pyrolysis Gasoline',
 'Pyrolysis oil',
 'Quicklime',
 'RBD palm olein',
 'RED BULL 250 ML (CH)',
 'Ranger energy drink',
 'Ranger functional energy drink',
 'Ready-to-Eat',
 'Ready-to-Eat Meal',
 'Rebar',
 'Rectified ceramic tile',
 'Rectified floor tile (size)',
 'Red Curry',
 'Refined',
 'Refined palm olein (from palm fruit)',
 'Riceberry Rice',
 'Round bag',
 'Round water hyacinth compact bag',
 'Round woven bag',
 'Rubber compound',
 'Rum raisin ice cream',
 'Sack',
 'Sheet paper hand towel',
 'Short-staple polyester fiber',
 'Singha Soda (brand)',
 'Singha sparkling water',
 'Single layer safety glass / Tempered glass',
 'Skincare',
 'Small pleated water hyacinth bag with Bodhi leaf leather strap',
 'Snack',
 'Soft drink',
 'Solid bleached sulfate (SBS)',
 'Soy milk',
 'Square bag with lid',
 'Square box bag',
 'Square water hyacinth bag with Dok Kaeo flower pattern',
 'Square woven bag',
 'Standard continuous form',
 'Standard continuous paper',
 'Steel can / Tin can',
 'Strawberry flavored yogurt',
 'Strawberry milk ice cream',
 'Strawberry yogurt',
 'Stretch kraft paper',
 'Stretchable kraft paper for industrial bags',
 'Sweet corn in brine',
 'Sweet corn kernels',
 'Sweetened santol',
 'Tableware',
 'Thai energy drink',
 'Tile',
 'Tin plated steel sheet',
 'Tinplate',
 'Tinplate can',
 'Toughened glass',
 'Treated nitric acid',
 'Triangle grass handbag mixed with genuine leather',
 'Tufted carpet tile',
 'Ultra-strong fluting',
 'Uncontrolled landfill',
 'Unlined continuous form',
 'VCM',
 'Vanilla flavored frozen dessert',
 'Vanilla milk ice cream',
 'Varnish',
 'Walking tractor use',
 'Wall ceramic tile',
 'Wall tile',
 'Water-based wax',
 'White box paperboard',
 'White box paperboard coated with starch /',
 'White lined chipboard (WLC)',
 'White liner paper for boxes',
 'White liner paper for boxes (weight)',
 'White top kraft',
 'Wire',
 "Women's woven bag",
 'Woven fabric (polyester yarn)',
 'Woven grass bag with leather',
 'Yellowish brown liner paper for boxes',
 'Yellowish brown liner paper for boxes (weight)',
 'Yellowish kraft liner',
 'Yen Ta Fo noodles',
 'bio-oil',
 'biofuel',
 'black circular pipe',
 'black rectangular pipe',
 'bottled water',
 'canned mackerel in tomato sauce',
 'caramelized sugar',
 'carbolic acid',
 'compounded rubber',
 "confectioners' sugar",
 'dehulled full-fat soybean',
 'deveined',
 'diesel fuel',
 'fluorescent light tube',
 'fresh milk',
 'glossy coated',
 'glucose syrup',
 'grey back',
 'heavy duty brass tee',
 'industrial filtered water',
 'low-fat fresh milk',
 'modular carpet',
 'o-xylene',
 'paraffin',
 'pink color',
 'polyester woven fabric',
 'polypropylene random copolymer pipe',
 'rubber block',
 'soybean milk',
 'sugar syrup',
 'sunflower oil',
 'tanker)',
 'tuna & salmon in jelly',
 'unrefined sugar',
 'virgin coconut oil',
 'white back',
 'zinc-coated steel pipe',
 'กรด',
 'กรดเทเรฟทาลิกบริสุทธิ์',
 'กรดไขมันจากปาล์ม',
 'กรดไขมันปาล์ม',
 'กรดไนตริกที่ผ่านกระบวนการปรับสภาพ',
 'กรดไนตริกปรับสภาพ',
 'กรอบทะเบียนรถลาย',
 'กรอบป้ายทะเบียนรถยนต์พิมพ์ลาย',
 'กรอบรูปกระดาษสามูลช้าง',
 'กรอบรูปจากกระดาษมูลช้าง',
 'กระจกกันร้อน',
 'กระจกฉนวนความร้อน',
 'กระจกนิรภัยชั้นเดียว',
 'กระจกนิรภัยหลายชั้น',
 'กระจกลามิเนต',
 'กระจกเทมเปอร์',
 'กระจังหน้าและกันชนหน้ารถสำหรับรถยนต์มาสด้า',
 'กระจาดไก่ทรงรี',
 'กระดาษ',
 'กระดาษกล่องขาวเคลือบมันหลังขาว',
 'กระดาษกล่องขาวเคลือบมันหลังเทา',
 'กระดาษกล่องขาวเคลือบแป้ง/',
 'กระดาษคราฟท์ทำถุง',
 'กระดาษคราฟท์ยืด',
 'กระดาษคราฟท์ยืดอุตสาหกรรม',
 'กระดาษคราฟท์สำหรับทำถุง/บรรจุภัณฑ์',
 'กระดาษคราฟท์สำหรับทำถุงอุตสาหกรรมชนิดยืด',
 'กระดาษคราฟท์เคลือบพลาสติก',
 'กระดาษคราฟท์เคลือบพลาสติกสำหรับทำถุง/',
 'กระดาษคราฟท์เคลือบพลาสติกสำหรับทำถุงอุตสาหกรรมชนิดยืด',
 'กระดาษคราฟท์เจาะรู',
 'กระดาษคราฟท์เจาะรูสำหรับทำถุงอุตสาหกรรมชนิดยืด',
 'กระดาษชำระแบบม้วนใหญ่',
 'กระดาษซับมือ',
 'กระดาษต่อเนื่อง',
 'กระดาษต่อเนื่องทั่วไป',
 'กระดาษต่อเนื่องมาตรฐาน',
 'กระดาษต่อเนื่องเคมีไม่มีเส้น',
 'กระดาษต่อเนื่องเปล่า',
 'กระดาษต่อเนื่องไม่มีเส้น',
 'กระดาษทำผิวกล่องขาว',
 'กระดาษทำผิวกล่องน้ำตาล',
 'กระดาษทำผิวกล่องน้ำตาลอ่อน',
 'กระดาษทำผิวกล่องพรีเมี่ยมเกรดสีขาว',
 'กระดาษทำผิวกล่องพรีเมี่ยมเกรดสีเหลืองทอง',
 'กระดาษทำผิวกล่องพรีเมี่ยมเกรดสีเหลืองทองน้ำหนัก',
 'กระดาษทำผิวกล่องสีขาว',
 'กระดาษทำผิวกล่องสีขาวน้ำหนัก',
 'กระดาษทำผิวกล่องสีทอง',
 'กระดาษทำผิวกล่องสีน้ำตาล',
 'กระดาษทำผิวกล่องสีน้ำตาลอมเหลือง',
 'กระดาษทำผิวกล่องสีน้ำตาลอมเหลืองน้ำหนัก',
 'กระดาษทำผิวกล่องสีน้ำตาลอ่อน',
 'กระดาษทำผิวกล่องสีน้ำตาลอ่อนเกรด',
 'กระดาษทำผิวกล่องสีเหลืองทอง',
 'กระดาษทำผิวกล่องสีเหลืองทองน้ำหนัก',
 'กระดาษทำผิวกล่องสีเหลืองอมน้ำตาล',
 'กระดาษทำลอนลูกฟูกความแข็งแรงสูง',
 'กระดาษทำลอนลูกฟูกความแข็งแรงสูงน้ำหนัก',
 'กระดาษทำลอนลูกฟูกความแข็งแรงสูงสุด',
 'กระดาษทำลอนลูกฟูกน้ำหนัก',
 'กระดาษทำลอนลูกฟูกเกรด',
 'กระดาษทิชชูม้วนใหญ่',
 'กระดาษทิชชูอุตสาหกรรม',
 'กระดาษพิมพ์ต่อเนื่อง',
 'กระดาษพิมพ์เขียนแบบ',
 'กระดาษพิมพ์เขียนแบบเคลือบผิว',
 'กระดาษมูลช้าง',
 'กระดาษยิปซัมด้านหน้า',
 'กระดาษยิปซัมด้านหลัง',
 'กระดาษลูกฟูก',
 'กระดาษลูกฟูกเกรด',
 'กระดาษลูกฟูกแข็งแรงพิเศษ',
 'กระดาษลูกฟูกแข็งแรงสูง',
 'กระดาษสามูลช้าง',
 'กระดาษสำหรับทำแผ่นยิปซั่มด้านหน้า',
 'กระดาษสำหรับทำแผ่นยิปซั่มด้านหลัง',
 'กระดาษเขียนแบบ',
 'กระดาษเขียนแบบเคลือบ',
 'กระดาษเคมีไม่มีเส้น',
 'กระดาษเช็ดมือแบบแผ่น',
 'กระดาษเช็ดอุตสาหกรรมแบบม้วน',
 'กระดาษแข็งขาวเคลือบแป้ง',
 'กระทิงแดง',
 'กระท้อนแก้ว',
 'กระท้อนแช่อิ่ม',
 'กระป๋องน้ำอัดลม',
 'กระป๋องอลูมิเนียม',
 'กระป๋องอลูมิเนียมพร้อมฝา',
 'กระป๋องอลูมิเนียมมีฝา',
 'กระป๋องเครื่องดื่ม',
 'กระป๋องเหล็ก',
 'กระป๋องและฝาอลูมิเนียม',
 'กระป๋องโลหะ',
 'กระเบื้อง',
 'กระเบื้องขอบคม',
 'กระเบื้องคอนกรีตเรียบ',
 'กระเบื้องซีเมนต์ปูพื้น',
 'กระเบื้องดินเผา',
 'กระเบื้องตัดขอบปูพื้นขนาด',
 'กระเบื้องติดผนัง',
 'กระเบื้องบุผนัง',
 'กระเบื้องปูพื้น',
 'กระเบื้องปูพื้นขอบคม',
 'กระเบื้องพอร์ซเลน',
 'กระเบื้องพื้น',
 'กระเบื้องพื้นซีเมนต์',
 'กระเบื้องมุงหลังคาคอนกรีต',
 'กระเบื้องหลังคาคอนกรีต',
 'กระเบื้องหลังคาคอนกรีตแบบเรียบ',
 'กระเบื้องหลังคาซีเมนต์',
 'กระเบื้องหลังคาพร้อมครอบ',
 'กระเบื้องหลังคาเซรามิค',
 'กระเบื้องหลังคาเซรามิคและครอบ',
 'กระเบื้องหลังคาไฟเบอร์ซีเมนต์',
 'กระเบื้องเซรามิคตัดขอบ',
 'กระเบื้องแกรนิตโต้',
 'กระเบื้องโมเสค',
 'กระเป๋าตอกลายดอกไม้',
 'กระเป๋าถือหญ้าสามเหลี่ยมผสมหนังแท้',
 'กระเป๋าถุง',
 'กระเป๋าทรงกลม',
 'กระเป๋าทรงกล่อง',
 'กระเป๋าทรงรีหูถือ',
 'กระเป๋าทรงวงรี',
 'กระเป๋าผักตบชวาตลับกลม',
 'กระเป๋าผักตบชวาตลับนาง',
 'กระเป๋าผักตบชวาทรงกะหรี่ปั๊บ',
 'กระเป๋าผักตบชวาทรงครึ่งวงกลมจิ๋ว',
 'กระเป๋าผักตบชวาทรงจีบเล็กสายหนังใบโพธิ์',
 'กระเป๋าผักตบชวาทรงสี่เหลี่ยมลายดอกแก้ว',
 'กระเป๋าผักตบชวาทรงสี่เหลี่ยมเปรมจิต',
 'กระเป๋าผักตบชวาหูถือทรงกะเหรี่ยง',
 'กระเป๋าลายดอกไม้',
 'กระเป๋าสานทรงกะเหรี่ยง',
 'กระเป๋าสานทรงครึ่งวงกลม',
 'กระเป๋าสานทรงเหลี่ยม',
 'กระเป๋าสานผักตบชวา',
 'กระเป๋าสานผู้หญิง',
 'กระเป๋าสานลายดอกไม้',
 'กระเป๋าสานสายหนัง',
 'กระเป๋าสานใบเล็ก',
 'กระเป๋าสี่เหลี่ยมฝาปิด',
 'กระเป๋าหญ้าผสมหนัง',
 'กระเป๋าใส่ปฏิทิน',
 'กล่องขาวหลังขาว',
 'กล่องขาวหลังเทา',
 'กากจากการแตกตัว',
 'การทิ้งขยะแบบเปิด',
 'การใช้รถไถเดินตาม',
 'ข้าวโพดกระป๋อง',
 'ข้าวโพดหวานกระป๋อง',
 'คิงส์สเตลล่า',
 'ชุดแต่งหน้ารถมาสด้า',
 'ซีเอ็กซ์',
 'ด้ายโพลีเอสเตอร์',
 'ตะกร้าไก่ทรงรี',
 'ถนอมอาหาร',
 'ถุงผ้า',
 'ถุงมือแพทย์',
 'ถุงใส่ปฏิทิน',
 'ถ่าน',
 'ทูน่าแซลมอนเจลลี่',
 'น้ำดื่ม',
 'น้ำตาลขาว',
 'น้ำตาลดิบ',
 'น้ำตาลทราย',
 'น้ำมันก๊าด',
 'น้ำมันคาโนล่า',
 'น้ำมันดอกทานตะวัน',
 'น้ำมันทานตะวัน',
 'น้ำมันปาล์ม',
 'น้ำมันปาล์มบริสุทธิ์',
 'น้ำมันปาล์มโอเลอิน',
 'น้ำมันมะพร้าวบริสุทธิ์',
 'น้ำมันมะพร้าวสกัดเย็น',
 'น้ำยาง HA',
 'น้ำยาง LA',
 'น้ำหวาน',
 'น้ำอัดลม',
 'น้ำอัดลมเอส',
 'น้ำเชื่อม',
 'น้ำโซดาสิงห์',
 'บรรจุภัณฑ์อลูมิเนียม',
 'บริการคลังสินค้า',
 'บัวลอยเผือก',
 'บิวทีน-1',
 'ปุ๋ยอินทรีย์',
 'ปูนขาว',
 'ปูนดิบ',
 'ผงซักฟอกเปา',
 'ผัดไทย',
 'ผ่านการย่อยด้วยน้ำ',
 'ผ้าถักฝ้าย',
 'ผ้าถักโพลีเอสเตอร์',
 'ผ้าทอฝ้าย',
 'ผ้าทอโพลีเอสเตอร์',
 'ผ้าบาติก',
 'ผ้าไหมมัดหมี่',
 'พรม',
 'พรมกระเบื้องทอ',
 'พรมปูพื้น',
 'พรมแผ่น',
 'พริกบดดอง',
 'พลาสติกชีวภาพ',
 'พอลิไวนิลคลอไรด์เรซิน',
 'พาเลทไม้อัด',
 'พีทีเอ (PTA)',
 'พีวีซีเรซิน',
 'ฟีนอล',
 'ภูสอยดาว',
 'มอลโทเดกซ์ทริน',
 'มาม่าคัพเล็ก',
 'มาม่าต้มยำกุ้ง',
 'มายองเนส',
 'ยางก้อน',
 'ยางคอมปาวด์',
 'ยางผสม',
 'ยางเครป',
 'ยางเรเดียล',
 'ยาสีฟัน',
 'ยูเนี่ยนโซลูชั่น',
 'รีฟอร์เมต',
 'ลวดหนามเทวดา',
 'ลวดเชื่อมไฟฟ้า',
 'ลีโอแบบกระป๋อง',
 'ลูกชิ้นปลา',
 'ลูกบดมากอตโต',
 'วัสดุกันเสียง',
 'สละลอยแก้ว',
 'สับปะรดกระป๋อง',
 'สามทางทองเหลืองหนา',
 'สารละลายกรด',
 'สารส้ม',
 'สีจระเข้',
 'สีชมพู',
 'สีรองพื้นกันด่าง',
 'สีรองพื้นเบเยอร์',
 'สุขภัณฑ์',
 'หน้าต่าง',
 'หมูดำ',
 'หมูบดชีวา',
 'หลอดฟลูออเรสเซนต์',
 'หินปูน',
 'ออกซิเจนเหลว',
 'ออร์โธไซลีน',
 'อะซิโตน',
 'อาร์กอนเหลว',
 'อาหารสุกร',
 'อิฐ',
 'อิฐมวลเบา',
 'อีเทน',
 'อีแอล-ลีน',
 'อีแอล-โปร',
 'อีโคสเฟียร์',
 'เกลือบริโภค',
 'เกลือแกง',
 'เครื่องดื่มกระทิงแดง',
 'เครื่องดื่มชูกำลัง',
 'เครื่องดื่มเรนเจอร์',
 'เค้กหินอ่อนช็อกโกแลต',
 'เค้กเนย',
 'เบียร์ช้าง',
 'เบียร์ลีโอ',
 'เบียร์สิงห์',
 'เมทิลเอสเทอร์',
 'เมล็ดข้าวโพดหวาน',
 'เม็ดพลาสติก HDPE',
 'เม็ดพลาสติก LLDPE',
 'เม็ดพลาสติก PET',
 'เม็ดพลาสติก PP',
 'เม็ดพลาสติกรีไซเคิล',
 'เส้นลวด',
 'เส้นไหม',
 'เหล็กซีมีปีก',
 'เหล็กเส้นข้ออ้อย',
 'เหล็กแท่งยาว',
 'เหล็กแบนรีด',
 'เหล็กแผ่นดำ',
 'เหล็กแผ่นรีดร้อน',
 'เอทานอลบริสุทธิ์',
 'เอทิลีน',
 'เอทิลีนออกไซด์',
 'เอ็มเอ็มเอ (MMA)',
 'แก๊สไฮโดรเจน',
 'แคลเซียมคาร์บอเนต',
 'แบรนด์วีต้า',
 'แป้งถั่วเขียวตราต้นสน',
 'แผ่น MDF',
 'แผ่นกระจกโมเดน',
 'แผ่นกระดาษ',
 'แผ่นกระเบื้อง',
 'แผ่นซับเสียง',
 'แผ่นพื้นคอนกรีตกลวง',
 'แผ่นอะคริลิก',
 'แฟตตี้',
 'แฟตตี้แอลกอฮอล์',
 'แว็กซ์น้ำ',
 'โค้ก',
 'โค้กขวด',
 'โพรพีน',
 'โมเสค',
 'โยเกิร์ตรสธรรมชาติ',
 'โยเกิร์ตรสสตรอเบอร์รี่',
 'โอเลอินปาล์ม',
 'ใยสังเคราะห์โพลีเอสเตอร์สั้น',
 'ไบโอดีเซล FAME',
 'ไม้ปาร์ติเกิล',
 'ไวนิลคลอไรด์โมโนเมอร์',
 'ไอศกรีมกาแฟอัลมอนด์',
 'ไอศกรีมคุกกี้แอนด์ครีม',
 'ไอศกรีมดัดแปลงรสวานิลลา',
 'ไอศกรีมนม',
 'ไอศกรีมนมชาเขียว',
 'ไอศกรีมนมช็อกโกแลต',
 'ไอศกรีมนมผสมกลิ่นวานิลลา',
 'ไอศกรีมนมผสมกาแฟโกปิโก้อัลมอนด์',
 'ไอศกรีมนมผสมคุ้กกี้&ครีม',
 'ไอศกรีมนมผสมชาเขียว',
 'ไอศกรีมนมผสมช็อกโกแลต',
 'ไอศกรีมนมผสมรัมเรซิ่น',
 'ไอศกรีมนมผสมสตรอว์เบอร์รี',
 'ไอศกรีมนมรัมเรซิ่น',
 'ไอศกรีมนมวานิลลา',
 'ไอศกรีมนมสด',
 'ไอศกรีมนมสตรอเบอร์รี่',
 'ไอศกรีมรสนมสด',
 'ไอศกรีมรสไขมันนม',
 'ไอศกรีมวานิลลาเทียม',
 'ไฮ-ป้อง',
 'ไฮ-ป้อง (ชื่อเฉพาะ)',
 'ไฮดอล',
 'ไฮดอล (ชื่อเฉพาะ)',
 'ไฮเปอร์-โลว์',
 'ไฮเปอร์-โลว์ (ชื่อเฉพาะ)',
 'ไฮโดรเจน',
 'ไฮโดรเเว๊กซ์',
 'ไฮโดรไลซ์'}

In [46]:
columns_to_check = set(word_dup)
df_cleaned = df.drop_duplicates(subset=columns_to_check, keep='first')

KeyError: Index(['กระดาษมูลช้าง', 'Kratingdaeng / Red Bull (Thai)',
       'ไวนิลคลอไรด์โมโนเมอร์', 'fluorescent light tube', 'เอทานอลบริสุทธิ์',
       'Sweet corn kernels', 'น้ำมันมะพร้าวสกัดเย็น', 'อาร์กอนเหลว',
       'Canned sweet corn', 'แผ่นซับเสียง',
       ...
       'Green tea milk ice cream', 'ลวดหนามเทวดา',
       'ใยสังเคราะห์โพลีเอสเตอร์สั้น', 'Coated drafting paper',
       'Aluminium tin', 'HDPE pellets', 'น้ำมันก๊าด',
       'Woven fabric (polyester yarn)', 'กระเป๋าทรงรีหูถือ',
       'กล่องขาวหลังขาว'],
      dtype='object', length=763)

In [30]:
for key,val in dup.items():
    if val > 1 :
        print(key,", ",val)

Bisphenol A ,  2
BPA ,  3
Brick ,  2
อิฐ ,  2
Butene-1 ,  2
บิวทีน-1 ,  2
1-บิวทีน ,  2
Calcium carbonate ,  2
แคลเซียมคาร์บอเนต ,  2
Limestone ,  3
หินปูน ,  3
ถ่าน ,  2
Cracker Bottom ,  2
กากจากการแตกตัว ,  2
CX ,  2
ซีเอ็กซ์ ,  2
Ethanol ,  2
MEG ,  2
Ethylene oxide ,  2
เอทิลีนออกไซด์ ,  2
Oxirane ,  2
Galvanized steel sheet ,  2
Hydrogen ,  3
ไฮโดรเจน ,  3
H2 ,  3
แก๊สไฮโดรเจน ,  3
K2CO3 ,  2
Kerosene ,  2
น้ำมันก๊าด ,  2
เครื่องดื่มชูกำลัง ,  2
ถุงมือแพทย์ ,  2
Light ENP@R ,  2
ปูนขาว ,  3
Quicklime ,  2
ปูนดิบ ,  2
Tufted carpet tile ,  2
พรมกระเบื้องทอ ,  2
Instant noodles ,  2
Mixed ENP@R ,  2
Mixed Xylene ,  2
Monosodium Phosphate ,  2
Montania ,  2
MOP ,  3
PharmaMOP ,  2
MTBE (methyl tert-butyl ether) ,  2
NAMECO ,  2
Natural ,  2
Nitric acid ,  2
Nitrogen ,  2
Non-Aromatics Mixture (CMix) ,  2
Nylon 6 ,  2
Offset laminated-Die cut-Corrugated Carton ,  2
OMEPRAZOLE 20 mg ,  2
Orthoxylene ,  3
ออร์โธไซลีน ,  3
o-xylene ,  2
Oxygen ,  2
Palm kernel shell ,  2
Palm kernel shell (CO2only) ,  2
Paraffin wax ,  2
paraffin ,  2
Paraquat ,  2
PE ,  2
PE Foam ,  2
PET PREFORM 600 29/25 Clear 13.5g. Manu. ,  2
Phenol ,  3
ฟีนอล ,  3
carbolic acid ,  2
Phosphoric acid ,  2
Phthalic anhydride ,  2
Pig ,  2
Polo Upcycling by GC ,  2
Polybutadiene ,  2
Polycarbonate ,  2
Polyester resin ,  2
Polyethylene terephthalate (PET) ,  2
Polypropylene (PP) ,  2
POLYSWABS ,  2
3" ,  2
THIN FLEXIBLE PADDLE TIP HT1530T ,  2
Polyurethane (flexible polyurethane) ,  2
Polyurethane (rigid urethane board) ,  2
Potassium hydroxide ,  2
Precast CAST14 ,  2
Preservative (Benzaldehyde) ,  2
Preservative (Bisphenol A) ,  2
Preservative (Wood preservative) ,  2
Propylene Oxide (PO) ,  2
PO ,  2
Purified terephthalic acid ,  4
กรดเทเรฟทาลิกบริสุทธิ์ ,  3
PTA ,  4
Purified Terephthalic Acid : PTA ,  2
Pyrolysis Gasoline ,  2
RED BULL 250 ML (CH) ,  2
Refined ,  2
เกลือแกง ,  2
เกลือบริโภค ,  2
Varnish ,  2
ไวนิลคลอไรด์โมโนเมอร์ ,  2
VCM ,  2
เค้กเนย ,  2
Chocolate marble cake ,  2
Marble chocolate cake ,  2
เค้กหินอ่อนช็อกโกแลต ,  2
Est drink ,  2
Est soft drink ,  2
น้ำอัดลมเอส ,  2
Beverage ,  2
น้ำดื่ม ,  2
Coca-Cola ,  2
โค้ก ,  3
Japanese green tea ,  2
Organic brown rice milk ,  2
Soft drink ,  2
น้ำอัดลม ,  2
Ranger functional energy drink ,  2
Ranger energy drink ,  2
เครื่องดื่มเรนเจอร์ ,  2
ลูกชิ้นปลา ,  3
Chicken ,  7
Chang Classic Beer ,  2
Chang beer ,  2
เบียร์ช้าง ,  2
เบียร์ลีโอ ,  2
Leo beer can ,  2
ลีโอแบบกระป๋อง ,  2
เบียร์สิงห์ ,  2
Live poultry ,  2
Cleaned fresh duck ,  2
Linear low-density polyethylene plastic pellets ,  2
LLDPE pellets ,  2
เม็ดพลาสติก LLDPE ,  2
High-density polyethylene plastic pellets ,  2
HDPE pellets ,  2
เม็ดพลาสติก HDPE ,  2
Polyethylene terephthalate plastic pellets ,  2
PET pellets ,  2
เม็ดพลาสติก PET ,  2
Polypropylene plastic pellets ,  4
PP pellets ,  4
เม็ดพลาสติก PP ,  4
PP compound ,  2
เม็ดพลาสติกรีไซเคิล ,  2
เมทิลเอสเทอร์ ,  2
MMA ,  2
เอ็มเอ็มเอ (MMA) ,  2
Latex ,  2
Short-staple polyester fiber ,  2
Polyester staple fiber (PSF) ,  2
ใยสังเคราะห์โพลีเอสเตอร์สั้น ,  2
เส้นไหม ,  2
Dried rice noodles ,  2
Polyester yarn ,  2
Polyester thread ,  2
ด้ายโพลีเอสเตอร์ ,  2
Poly-cotton yarn ,  2
เส้นลวด ,  2
Wire ,  2
Yen Ta Fo noodles ,  2
เหล็กเส้นข้ออ้อย ,  2
Deformed steel bar ,  2
Rebar ,  2
เหล็กแผ่นรีดร้อน ,  3
เหล็กแท่งยาว ,  2
เหล็กแผ่นดำ ,  4
เหล็กแบนรีด ,  2
Tin plated steel sheet ,  2
Tinplate ,  2
Hot rolled steel sheet ,  2
HR steel sheet ,  2
เหล็กซีมีปีก ,  2
Ethylene ,  2
Ethene ,  2
เอทิลีน ,  3
เอทานอลบริสุทธิ์ ,  2
Brand ,  7
แบรนด์วีต้า ,  2
แป้งถั่วเขียวตราต้นสน ,  2
Packaged tapioca flour ,  2
Moden Glass (sheet) ,  2
แผ่นกระจกโมเดน ,  2
MDF ,  2
แผ่น MDF ,  2
Particleboard ,  2
Chipboard ,  2
ไม้ปาร์ติเกิล ,  2
แผ่นซับเสียง ,  2
Floor carpet ,  2
พรมปูพื้น ,  4
Hollow core precast concrete floor slab ,  2
Hollow core slab ,  2
แผ่นพื้นคอนกรีตกลวง ,  2
Acrylic sheet ,  2
แผ่นอะคริลิก ,  2
แฟตตี้ ,  2
แฟตตี้แอลกอฮอล์ ,  2
Coke ,  2
Singha Soda (brand) ,  2
Singha sparkling water ,  2
น้ำโซดาสิงห์ ,  2
Propylene ,  2
Propene ,  2
โพรพีน ,  2
Natural yogurt ,  2
Plain yogurt ,  2
โยเกิร์ตรสธรรมชาติ ,  3
Strawberry yogurt ,  2
Strawberry flavored yogurt ,  2
โยเกิร์ตรสสตรอเบอร์รี่ ,  2
น้ำมันปาล์ม ,  2
Biodiesel of fatty acid methyl ester type ,  2
FAME biodiesel ,  2
ไบโอดีเซล FAME ,  2
Decorative flooring ,  2
Laminated rubberwood (grade) ,  2
Glued rubberwood ,  2
ไอศกรีมดัดแปลงรสวานิลลา ,  2
Modified vanilla ice cream ,  2
Vanilla flavored frozen dessert ,  2
ไอศกรีมวานิลลาเทียม ,  2
ไอศกรีมนม ,  2
Milk ice cream ,  2
Dairy ice cream ,  2
ไอศกรีมรสไขมันนม ,  2
ไอศกรีมนมผสมกลิ่นวานิลลา ,  2
Milk ice cream with vanilla flavor ,  2
Vanilla milk ice cream ,  2
ไอศกรีมนมวานิลลา ,  2
ไอศกรีมนมผสมกาแฟโกปิโก้อัลมอนด์ ,  2
Milk ice cream with Kopiko coffee almond ,  2
Coffee almond ice cream ,  2
ไอศกรีมกาแฟอัลมอนด์ ,  2
ไอศกรีมนมผสมคุ้กกี้&ครีม ,  2
Milk ice cream with cookies & cream ,  2
Cookies and cream ice cream ,  2
ไอศกรีมคุกกี้แอนด์ครีม ,  2
ไอศกรีมนมผสมช็อกโกแลต ,  2
Milk ice cream with chocolate ,  2
Chocolate milk ice cream ,  2
ไอศกรีมนมช็อกโกแลต ,  2
ไอศกรีมนมผสมชาเขียว ,  2
Milk ice cream with green tea ,  2
Green tea milk ice cream ,  2
ไอศกรีมนมชาเขียว ,  2
ไอศกรีมนมผสมรัมเรซิ่น ,  2
Milk ice cream with rum raisin ,  2
Rum raisin ice cream ,  2
ไอศกรีมนมรัมเรซิ่น ,  2
ไอศกรีมนมผสมสตรอว์เบอร์รี ,  2
Milk ice cream with strawberry ,  2
Strawberry milk ice cream ,  2
ไอศกรีมนมสตรอเบอร์รี่ ,  2
ไอศกรีมนมสด ,  2
Fresh milk ice cream ,  2
Fresh dairy ice cream ,  2
ไอศกรีมรสนมสด ,  2
ไฮเปอร์-โลว์ ,  2
Hyper-Low ,  2
ไฮเปอร์-โลว์ (ชื่อเฉพาะ) ,  2
ไฮโดรเเว๊กซ์ ,  2
Hydrowax ,  2
Water-based wax ,  2
แว็กซ์น้ำ ,  2
ไฮโดรไลซ์ ,  2
Hydrolyzed ,  2
Hydrolysed ,  2
ผ่านการย่อยด้วยน้ำ ,  2
ไฮดอล ,  2
Hydol ,  2
ไฮดอล (ชื่อเฉพาะ) ,  2
ไฮ-ป้อง ,  2
High-Pong ,  2
ไฮ-ป้อง (ชื่อเฉพาะ) ,  2
กรด ,  2
Acid ,  2
Chemical acid ,  2
สารละลายกรด ,  2
พีทีเอ (PTA) ,  2
กรดไขมันปาล์ม ,  2
Palm fatty acid ,  2
Palm oil fatty acid ,  2
กรดไขมันจากปาล์ม ,  2
กรดไนตริกที่ผ่านกระบวนการปรับสภาพ ,  2
Conditioned nitric acid ,  2
Treated nitric acid ,  2
กรดไนตริกปรับสภาพ ,  2
กรอบป้ายทะเบียนรถยนต์พิมพ์ลาย ,  2
Printed pattern car license plate frame ,  2
Custom license plate frame ,  2
กรอบทะเบียนรถลาย ,  2
กรอบรูปกระดาษสามูลช้าง ,  2
Elephant dung paper photo frame ,  2
Eco-friendly photo frame ,  2
กรอบรูปจากกระดาษมูลช้าง ,  2
กระเบื้อง ,  2
Tile ,  2
Ceramic tile ,  2
แผ่นกระเบื้อง ,  2
กระเบื้องเซรามิคตัดขอบ ,  2
Rectified ceramic tile ,  2
Precision-cut ceramic tile ,  2
กระเบื้องขอบคม ,  2
กระเบื้องโมเสค ,  2
Mosaic tile ,  2
Mosaic ,  2
โมเสค ,  2
กระเบื้องซีเมนต์ปูพื้น ,  2
Cement floor tile ,  2
Concrete tile ,  2
กระเบื้องพื้นซีเมนต์ ,  2
กระเบื้องตัดขอบปูพื้นขนาด ,  2
Rectified floor tile (size) ,  2
Precision-cut floor tile ,  2
กระเบื้องปูพื้นขอบคม ,  2
กระเบื้องบุผนัง ,  2
Wall tile ,  2
Wall ceramic tile ,  2
กระเบื้องติดผนัง ,  2
กระเบื้องปูพื้น ,  2
Floor tile ,  2
Flooring tile ,  2
กระเบื้องพื้น ,  3
กระเบื้องพอร์ซเลน ,  2
Porcelain tile ,  2
Glazed porcelain tile ,  2
กระเบื้องแกรนิตโต้ ,  2
กระเบื้องหลังคาเซรามิค ,  2
Ceramic roof tile ,  2
Clay roof tile ,  2
กระเบื้องดินเผา ,  2
กระเบื้องหลังคาเซรามิคและครอบ ,  2
Ceramic roof tile and ridge cap ,  2
Ceramic roofing system ,  2
กระเบื้องหลังคาพร้อมครอบ ,  2
กระเบื้องหลังคาไฟเบอร์ซีเมนต์ ,  2
Fiber cement roof tile ,  2
Fibre cement roofing ,  2
กระเบื้องหลังคาซีเมนต์ ,  2
กระเบื้องหลังคาคอนกรีต ,  2
Concrete roof tile ,  2
Cement roof tile ,  2
กระเบื้องมุงหลังคาคอนกรีต ,  2
กระเบื้องหลังคาคอนกรีตแบบเรียบ ,  2
Flat concrete roof tile ,  2
Modern concrete tile ,  2
กระเบื้องคอนกรีตเรียบ ,  2
กระเป๋าใส่ปฏิทิน ,  2
Calendar bag / Calendar holder bag ,  2
Calendar pouch ,  2
ถุงใส่ปฏิทิน ,  2
กระเป๋าตอกลายดอกไม้ ,  2
Bag with floral embossed pattern ,  2
Embossed flower bag ,  2
กระเป๋าลายดอกไม้ ,  2
กระเป๋าถือหญ้าสามเหลี่ยมผสมหนังแท้ ,  2
Triangle grass handbag mixed with genuine leather ,  2
Woven grass bag with leather ,  2
กระเป๋าหญ้าผสมหนัง ,  2
กระเป๋าถุง ,  2
Bag / Pouch ,  2
Sack ,  2
ถุงผ้า ,  2
กระเป๋าทรงกลม ,  4
Round bag ,  2
Circle bag ,  2
กระเป๋าทรงรีหูถือ ,  2
Oval shaped handbag with handle ,  2
Oval tote bag ,  2
กระเป๋าทรงวงรี ,  2
กระเป๋าผักตบชวาตลับกลม ,  2
Round water hyacinth compact bag ,  2
Round woven bag ,  2
กระเป๋าสานผักตบชวา ,  2
กระเป๋าผักตบชวาตลับนาง ,  2
Lady's water hyacinth compact bag ,  2
Women's woven bag ,  2
กระเป๋าสานผู้หญิง ,  2
กระเป๋าผักตบชวาทรงกะหรี่ปั๊บ ,  2
Curry puff-shaped water hyacinth bag ,  2
Crescent woven bag ,  2
กระเป๋าสานทรงครึ่งวงกลม ,  2
กระเป๋าผักตบชวาทรงครึ่งวงกลมจิ๋ว ,  2
Miniature half-circle water hyacinth bag ,  2
Mini crescent woven bag ,  2
กระเป๋าสานใบเล็ก ,  2
กระเป๋าผักตบชวาทรงจีบเล็กสายหนังใบโพธิ์ ,  2
Small pleated water hyacinth bag with Bodhi leaf leather strap ,  2
Pleated woven bag ,  2
กระเป๋าสานสายหนัง ,  2
กระเป๋าผักตบชวาทรงสี่เหลี่ยมเปรมจิต ,  2
Premjit square water hyacinth bag ,  2
Square woven bag ,  2
กระเป๋าสานทรงเหลี่ยม ,  2
กระเป๋าผักตบชวาทรงสี่เหลี่ยมลายดอกแก้ว ,  2
Square water hyacinth bag with Dok Kaeo flower pattern ,  2
Floral woven square bag ,  2
กระเป๋าสานลายดอกไม้ ,  2
กระเป๋าผักตบชวาหูถือทรงกะเหรี่ยง ,  2
Karen-style water hyacinth handbag with handle ,  2
Ethnic woven handbag ,  2
กระเป๋าสานทรงกะเหรี่ยง ,  2
กระเป๋าสี่เหลี่ยมฝาปิด ,  2
Square bag with lid ,  2
Square box bag ,  2
กระเป๋าทรงกล่อง ,  2
กระจกฉนวนความร้อน ,  2
Heat insulating glass / Insulated glass ,  2
Low-E glass ,  2
กระจกกันร้อน ,  2
กระจกนิรภัยชั้นเดียว ,  2
Single layer safety glass / Tempered glass ,  2
Toughened glass ,  2
กระจกเทมเปอร์ ,  2
กระจกนิรภัยหลายชั้น ,  2
Multi-layer safety glass / Laminated glass ,  2
Laminated safety glass ,  2
กระจกลามิเนต ,  2
กระจังหน้าและกันชนหน้ารถสำหรับรถยนต์มาสด้า ,  2
Front grille and front bumper for Mazda cars ,  2
Mazda front end ,  2
ชุดแต่งหน้ารถมาสด้า ,  2
กระจาดไก่ทรงรี ,  2
Oval chicken basket ,  3
Oval poultry basket ,  2
ตะกร้าไก่ทรงรี ,  3
กระดาษ ,  2
Paper ,  2
Paper sheet ,  2
แผ่นกระดาษ ,  2
กระดาษเช็ดมือแบบแผ่น ,  2
Sheet paper hand towel ,  2
Paper towels ,  2
กระดาษซับมือ ,  2
กระดาษเช็ดอุตสาหกรรมแบบม้วน ,  2
Industrial roll paper towel ,  2
Industrial paper wipes ,  2
กระดาษทิชชูอุตสาหกรรม ,  2
กระดาษกล่องขาวเคลือบแป้ง/ ,  2
White box paperboard coated with starch / ,  2
Coated white cardboard ,  2
กระดาษแข็งขาวเคลือบแป้ง ,  2
กระดาษกล่องขาวเคลือบมันหลังเทา ,  2
White box paperboard ,  4
glossy coated ,  4
grey back ,  2
White lined chipboard (WLC) ,  2
กล่องขาวหลังเทา ,  2
กระดาษกล่องขาวเคลือบมันหลังขาว ,  2
white back ,  2
Solid bleached sulfate (SBS) ,  2
กล่องขาวหลังขาว ,  2
กระดาษคราฟท์เคลือบพลาสติกสำหรับทำถุง/ ,  2
Plastic coated kraft paper for bag making / ,  2
Laminated kraft paper ,  2
กระดาษคราฟท์เคลือบพลาสติก ,  2
กระดาษคราฟท์เคลือบพลาสติกสำหรับทำถุงอุตสาหกรรมชนิดยืด ,  2
Plastic coated stretchable kraft paper for industrial bags ,  2
Stretch kraft paper ,  2
กระดาษคราฟท์ยืด ,  2
กระดาษคราฟท์เจาะรูสำหรับทำถุงอุตสาหกรรมชนิดยืด ,  2
Perforated stretchable kraft paper for industrial bags ,  2
Perforated industrial kraft ,  2
กระดาษคราฟท์เจาะรู ,  2
กระดาษคราฟท์สำหรับทำถุง/บรรจุภัณฑ์ ,  2
Kraft paper for bag making/packaging ,  2
Packaging kraft ,  2
กระดาษคราฟท์ทำถุง ,  2
กระดาษคราฟท์สำหรับทำถุงอุตสาหกรรมชนิดยืด ,  2
Stretchable kraft paper for industrial bags ,  2
Industrial stretch kraft ,  2
กระดาษคราฟท์ยืดอุตสาหกรรม ,  2
กระดาษชำระแบบม้วนใหญ่ ,  2
Jumbo roll toilet paper ,  2
Bulk toilet paper ,  2
กระดาษทิชชูม้วนใหญ่ ,  2
กระดาษต่อเนื่อง ,  2
Continuous paper / Continuous form ,  2
Dot matrix paper ,  2
กระดาษพิมพ์ต่อเนื่อง ,  2
กระดาษต่อเนื่องเคมีไม่มีเส้น ,  2
Continuous chemical paper without lines ,  2
Carbonless continuous form ,  2
กระดาษเคมีไม่มีเส้น ,  2
กระดาษต่อเนื่องไม่มีเส้น ,  2
Continuous paper without lines ,  2
Unlined continuous form ,  2
กระดาษต่อเนื่องเปล่า ,  2
กระดาษต่อเนื่องมาตรฐาน ,  2
Standard continuous paper ,  2
Standard continuous form ,  2
กระดาษต่อเนื่องทั่วไป ,  2
กระดาษทำผิวกล่องพรีเมี่ยมเกรดสีเหลืองทอง ,  2
Premium grade golden yellow liner paper for boxes ,  2
Golden liner board ,  8
กระดาษทำผิวกล่องสีทอง ,  8
กระดาษทำผิวกล่องพรีเมี่ยมเกรดสีเหลืองทองน้ำหนัก ,  2
Premium grade golden yellow liner paper for boxes (weight) ,  2
กระดาษทำผิวกล่องพรีเมี่ยมเกรดสีขาว ,  2
Premium grade white liner paper for boxes ,  2
Premium white liner ,  2
กระดาษทำผิวกล่องขาว ,  6
กระดาษทำผิวกล่องสีเหลืองทอง ,  2
Golden yellow liner paper for boxes ,  2
กระดาษทำผิวกล่องสีเหลืองทองน้ำหนัก ,  2
Golden yellow liner paper for boxes (weight) ,  2
กระดาษทำผิวกล่องสีขาว ,  2
White liner paper for boxes ,  2
White top kraft ,  4
กระดาษทำผิวกล่องสีขาวน้ำหนัก ,  2
White liner paper for boxes (weight) ,  2
กระดาษทำผิวกล่องสีน้ำตาล ,  2
Brown liner paper for boxes ,  2
Kraft liner board ,  2
กระดาษทำผิวกล่องน้ำตาล ,  2
กระดาษทำผิวกล่องสีน้ำตาลอมเหลือง ,  2
Yellowish brown liner paper for boxes ,  2
Yellowish kraft liner ,  4
กระดาษทำผิวกล่องสีเหลืองอมน้ำตาล ,  4
กระดาษทำผิวกล่องสีน้ำตาลอมเหลืองน้ำหนัก ,  2
Yellowish brown liner paper for boxes (weight) ,  2
กระดาษทำผิวกล่องสีน้ำตาลอ่อน ,  2
Light brown liner paper for boxes ,  2
Light kraft liner ,  4
กระดาษทำผิวกล่องน้ำตาลอ่อน ,  4
กระดาษทำผิวกล่องสีน้ำตาลอ่อนเกรด ,  2
Light brown liner paper for boxes (grade) ,  2
กระดาษทำลอนลูกฟูกเกรด ,  2
Corrugating medium paper (grade) ,  2
Fluting paper ,  4
กระดาษลูกฟูกเกรด ,  2
กระดาษทำลอนลูกฟูกความแข็งแรงสูง ,  2
High strength corrugating medium paper ,  2
High performance fluting ,  4
กระดาษลูกฟูกแข็งแรงสูง ,  4
กระดาษทำลอนลูกฟูกความแข็งแรงสูงน้ำหนัก ,  2
High strength corrugating medium paper (weight) ,  2
กระดาษทำลอนลูกฟูกความแข็งแรงสูงสุด ,  2
Maximum strength corrugating medium paper ,  2
Ultra-strong fluting ,  2
กระดาษลูกฟูกแข็งแรงพิเศษ ,  2
กระดาษทำลอนลูกฟูกน้ำหนัก ,  2
Corrugating medium paper (weight) ,  2
กระดาษลูกฟูก ,  2
กระดาษพิมพ์เขียนแบบ ,  2
Drafting paper / Blueprint paper ,  2
Engineering paper ,  2
กระดาษเขียนแบบ ,  2
กระดาษพิมพ์เขียนแบบเคลือบผิว ,  2
Coated drafting paper ,  2
Coated engineering paper ,  2
กระดาษเขียนแบบเคลือบ ,  2
กระดาษสามูลช้าง ,  2
Elephant dung paper ,  2
Elephant poop paper ,  2
กระดาษมูลช้าง ,  2
กระดาษสำหรับทำแผ่นยิปซั่มด้านหน้า ,  2
Paper for front side of gypsum board ,  2
Gypsum facing paper ,  2
กระดาษยิปซัมด้านหน้า ,  2
กระดาษสำหรับทำแผ่นยิปซั่มด้านหลัง ,  2
Paper for back side of gypsum board ,  2
Gypsum backing paper ,  2
กระดาษยิปซัมด้านหลัง ,  2
กระท้อนแก้ว ,  2
Glass santol / Candied santol ,  2
Sweetened santol ,  2
กระท้อนแช่อิ่ม ,  2
กระทิงแดง ,  2
Kratingdaeng / Red Bull (Thai) ,  2
Thai energy drink ,  2
เครื่องดื่มกระทิงแดง ,  2
กระป๋องเครื่องดื่ม ,  2
Beverage can ,  2
Drink can ,  2
กระป๋องน้ำอัดลม ,  2
กระป๋องเหล็ก ,  2
Steel can / Tin can ,  2
Tinplate can ,  2
กระป๋องโลหะ ,  2
กระป๋องและฝาอลูมิเนียม ,  2
Aluminum cans and lids ,  2
Aluminum packaging ,  2
บรรจุภัณฑ์อลูมิเนียม ,  2
กระป๋องอลูมิเนียม ,  4
Aluminum can ,  2
Aluminium tin ,  2
กระป๋องอลูมิเนียมพร้อมฝา ,  2
Aluminum can with lid ,  2
Lidded aluminum can ,  2
กระป๋องอลูมิเนียมมีฝา ,  2
Walking tractor use ,  2
การใช้รถไถเดินตาม ,  2
Open dumping of community solid waste ,  2
Uncontrolled landfill ,  2
การทิ้งขยะแบบเปิด ,  2
deveined ,  2
Sweet corn kernels ,  3
Corn kernels ,  2
เมล็ดข้าวโพดหวาน ,  2
Canned sweet corn ,  4
ข้าวโพดหวานกระป๋อง ,  2
Sweet corn in brine ,  2
ข้าวโพดกระป๋อง ,  2
Riceberry Rice ,  4
Grain ,  23
Bagged ,  6
Ready-to-Eat Meal ,  18
Brown Jasmine Rice ,  2
Snack ,  2
Ready-to-Eat ,  3
Panang Curry ,  2
Jasmine Rice ,  7
100% Jasmine Rice ,  2
Red Curry ,  2
Industrial Material ,  4
Food Brand ,  2
Industrial Chemical ,  3
Skincare ,  4
Chemical ,  2
Home & Building Materials ,  2
Packaging Material ,  4
Building Material ,  14
Automotive Part ,  2
คิงส์สเตลล่า ,  2
Embedded Aluminum Stair Nosing ,  2
Tableware ,  2
diesel fuel ,  2
Full-fat dehulled soybean ,  2
dehulled full-fat soybean ,  2
Galvanized steel pipe ,  3
zinc-coated steel pipe ,  2
black circular pipe ,  2
black rectangular pipe ,  2
PE pipe ,  2
PPR pipe ,  2
polypropylene random copolymer pipe ,  2
Soy milk ,  2
soybean milk ,  2
Pasteurized low-fat fresh milk ,  2
low-fat fresh milk ,  2
fresh milk ,  2
NBMA ,  2
น้ำเชื่อม ,  2
sugar syrup ,  2
glucose syrup ,  2
industrial filtered water ,  2
bottled water ,  2
Crystal drinking water ,  2
Crystal brand water ,  2
Caramel coated sugar ,  2
caramelized sugar ,  2
confectioners' sugar ,  2
น้ำตาลดิบ ,  2
น้ำตาลทราย ,  2
unrefined sugar ,  2
น้ำตาลขาว ,  2
Mitr Phol brown sugar ,  2
Mitr Phol natural cane sugar ,  2
Mitr Phol cane sugar ,  2
biofuel ,  2
น้ำมันดอกทานตะวัน ,  2
sunflower oil ,  2
Pyrolysis oil ,  2
bio-oil ,  2
น้ำมันคาโนล่า ,  2
น้ำมันทานตะวัน ,  2
น้ำมันปาล์มโอเลอิน ,  3
โอเลอินปาล์ม ,  2
น้ำมันปาล์มบริสุทธิ์ ,  2
Refined palm olein (from palm fruit) ,  3
RBD palm olein ,  3
tanker) ,  2
น้ำมันมะพร้าวบริสุทธิ์ ,  4
Pure coconut oil ,  2
น้ำมันมะพร้าวสกัดเย็น ,  2
virgin coconut oil ,  2
High ammonia concentrated latex ,  4
HA latex ,  4
น้ำยาง HA ,  3
น้ำยาง LA ,  2
Low ammonia concentrated latex ,  2
LA latex ,  2
ยางผสม ,  4
น้ำหวาน ,  2
โค้กขวด ,  2
Bottled Coca-Cola ,  2
Coke bottle ,  2
บริการคลังสินค้า ,  2
อิฐมวลเบา ,  2
AAC block ,  2
มาม่าคัพเล็ก ,  2
มาม่าต้มยำกุ้ง ,  2
บัวลอยเผือก ,  2
Mackerel in tomato sauce ,  2
canned mackerel in tomato sauce ,  2
ทูน่าแซลมอนเจลลี่ ,  2
tuna & salmon in jelly ,  2
ปุ๋ยอินทรีย์ ,  2
ผงซักฟอกเปา ,  2
Pao washing powder ,  2
หลอดฟลูออเรสเซนต์ ,  2
fluorescent light tube ,  2
ผัดไทย ,  2
ผ้าไหมมัดหมี่ ,  2
ผ้าถักโพลีเอสเตอร์ ,  2
ผ้าถักฝ้าย ,  2
ผ้าทอโพลีเอสเตอร์ ,  2
Woven fabric (polyester yarn) ,  2
polyester woven fabric ,  2
ผ้าทอฝ้าย ,  2
ผ้าบาติก ,  2
พรม ,  2
พรมแผ่น ,  2
Carpet tile ,  2
modular carpet ,  2
พริกบดดอง ,  2
ถนอมอาหาร ,  2
Preserve ,  2
พลาสติกชีวภาพ ,  2
พอลิไวนิลคลอไรด์เรซิน ,  2
พีวีซีเรซิน ,  2
PVC resin ,  2
พาเลทไม้อัด ,  2
สีชมพู ,  2
Pink ,  2
pink color ,  2
ภูสอยดาว ,  2
มอลโทเดกซ์ทริน ,  2
มายองเนส ,  2
ยางเครป ,  2
ยางเรเดียล ,  2
ยางก้อน ,  2
Block rubber ,  2
rubber block ,  2
ยางคอมปาวด์ ,  2
Rubber compound ,  2
compounded rubber ,  2
ยาสีฟัน ,  2
ยูเนี่ยนโซลูชั่น ,  2
รีฟอร์เมต ,  2
ลวดเชื่อมไฟฟ้า ,  2
ลวดหนามเทวดา ,  2
ลูกบดมากอตโต ,  2
วัสดุกันเสียง ,  2
สละลอยแก้ว ,  2
สับปะรดกระป๋อง ,  2
Canned pineapple slices in clear syrup ,  2
สามทางทองเหลืองหนา ,  2
heavy duty brass tee ,  2
สารส้ม ,  2
สีจระเข้ ,  2
สีรองพื้นกันด่าง ,  2
สีรองพื้นเบเยอร์ ,  2
สุขภัณฑ์ ,  2
หน้าต่าง ,  2
หมูดำ ,  2
หมูบดชีวา ,  2
ออกซิเจนเหลว ,  2
อะซิโตน ,  2
อาร์กอนเหลว ,  2
อาหารสุกร ,  2
อีเทน ,  2
อีแอล-โปร ,  2
อีแอล-ลีน ,  2
อีโคสเฟียร์ ,  2

In [ ]:
long_list = new.values.flatten().tolist()
raw_word = list()
for word in long_list:
    if pd.notna(word) and isinstance(word, str):
        raw_word.append(str(word.strip()))

7395

In [49]:
import pandas as pd

def clean_duplicate_words_anywhere(df, target_word):
   """
   ลบคำซ้ำจากทั้ง DataFrame 
   - เก็บแถวแรกที่มีคำที่ต้องการ และแก้ไขให้เก็บคำนั้นตัวแรกเท่านั้น
   - ลบแถวอื่นๆ ที่มีคำนั้นออกทั้งหมด
   - เก็บแถวที่ไม่มีคำนั้นไว้
   """
   
   # ฟังก์ชันตรวจสอบว่าแถวมีคำที่ต้องการหรือไม่
   def has_word_in_row(row):
       for value in row:
           if pd.notna(value) and target_word in str(value).split():
               return True
       return False
   
   # ฟังก์ชันลบคำซ้ำในแถว เก็บตัวแรกไว้
   def clean_row(row):
       first_found = False
       cleaned_row = row.copy()
       
       for col_name in row.index:
           if pd.notna(row[col_name]):
               text = str(row[col_name])
               words = text.split()
               result = []
               
               for word in words:
                   if word == target_word:
                       if not first_found:
                           result.append(word)
                           first_found = True
                       # ข้ามคำที่ซ้ำ
                   else:
                       result.append(word)
               
               cleaned_row[col_name] = ' '.join(result)
       
       return cleaned_row
   
   # หาแถวที่มีคำที่ต้องการ
   has_word_mask = df.apply(has_word_in_row, axis=1)
   
   if has_word_mask.any():
       # หาแถวแรกที่มีคำที่ต้องการ
       first_word_index = df[has_word_mask].index[0]
       
       # สร้าง copy ของ DataFrame
       df_result = df.copy()
       
       # แก้ไขแถวแรก - เก็บคำที่ต้องการตัวแรกเท่านั้น
       df_result.loc[first_word_index] = clean_row(df_result.loc[first_word_index])
       
       # เก็บเฉพาะแถวที่ต้องการ (แถวแรกที่มีคำ + แถวที่ไม่มีคำนั้น)
       mask = (df_result.index == first_word_index) | (~has_word_mask)
       return df_result[mask]
   else:
       return df  # ถ้าไม่มีคำที่ต้องการเลย

# ตัวอย่างการใช้งาน
sample_data = {
   'col1': ['กรดน้ำส้ม ดาน อินทรีย์', 'สารเคมี', 'เอทานอล ตัวทำละลาย', 'กรด ดาน', 'ดาน เคมี'],
   'col2': ['เคมี อนินทรีย์', 'ดาน ตัวทำละลาย ดาน', 'อินทรีย์', 'สาร ดาน อนินทรีย์', 'น้ำ'],
   'col3': ['ตัวทำละลาย', 'อนินทรีย์ ดาน', 'เคมี ดาน ดาน', 'สาร', 'ตัวทำละลาย ดาน ดาน ดาน']
}

df = pd.DataFrame(sample_data)
print("ข้อมูลเดิม:")
print(df)

# ใช้งาน
df_cleaned = clean_duplicate_words_anywhere(df, 'ดาน')
print("\nหลังทำความสะอาดคำ 'ดาน':")
print(df_cleaned)

# ใช้กับคำอื่น
df_cleaned2 = clean_duplicate_words_anywhere(df, 'เคมี')
print("\nหลังทำความสะอาดคำ 'เคมี':")
print(df_cleaned2)

df_cleaned2

ข้อมูลเดิม:
                     col1                col2                    col3
0  กรดน้ำส้ม ดาน อินทรีย์      เคมี อนินทรีย์              ตัวทำละลาย
1                 สารเคมี  ดาน ตัวทำละลาย ดาน           อนินทรีย์ ดาน
2      เอทานอล ตัวทำละลาย            อินทรีย์            เคมี ดาน ดาน
3                 กรด ดาน   สาร ดาน อนินทรีย์                     สาร
4                ดาน เคมี                 น้ำ  ตัวทำละลาย ดาน ดาน ดาน

หลังทำความสะอาดคำ 'ดาน':
                     col1            col2        col3
0  กรดน้ำส้ม ดาน อินทรีย์  เคมี อนินทรีย์  ตัวทำละลาย

หลังทำความสะอาดคำ 'เคมี':
                     col1                col2           col3
0  กรดน้ำส้ม ดาน อินทรีย์      เคมี อนินทรีย์     ตัวทำละลาย
1                 สารเคมี  ดาน ตัวทำละลาย ดาน  อนินทรีย์ ดาน
3                 กรด ดาน   สาร ดาน อนินทรีย์            สาร

                     col1                col2           col3
0  กรดน้ำส้ม ดาน อินทรีย์      เคมี อนินทรีย์     ตัวทำละลาย
1                 สารเคมี  ดาน ตัวทำละลาย ดาน  อนินทรีย์ ดาน
3                 กรด ดาน   สาร ดาน อนินทรีย์            สาร

In [50]:
import pandas as pd

def clean_multiple_words_anywhere(df, word_list):
   """
   ลบคำซ้ำหลายคำพร้อมกันจากทั้ง DataFrame 
   - เก็บแถวแรกที่มีแต่ละคำ และแก้ไขให้เก็บคำนั้นตัวแรกเท่านั้น
   - ลบแถวอื่นๆ ที่มีคำเหล่านั้นออกทั้งหมด
   - เก็บแถวที่ไม่มีคำเหล่านั้นไว้
   """
   
   # ฟังก์ชันตรวจสอบว่าแถวมีคำใดๆ ในรายการหรือไม่
   def has_any_word_in_row(row, words):
       for value in row:
           if pd.notna(value):
               text_words = str(value).split()
               for word in words:
                   if word in text_words:
                       return True, word
       return False, None
   
   # ฟังก์ชันลบคำซ้ำทั้งหมดในแถว เก็บตัวแรกของแต่ละคำไว้
   def clean_row_multiple_words(row, words):
       word_found = {word: False for word in words}
       cleaned_row = row.copy()
       
       for col_name in row.index:
           if pd.notna(row[col_name]):
               text = str(row[col_name])
               text_words = text.split()
               result = []
               
               for word in text_words:
                   if word in words:
                       if not word_found[word]:
                           result.append(word)
                           word_found[word] = True
                       # ข้ามคำที่ซ้ำ
                   else:
                       result.append(word)
               
               cleaned_row[col_name] = ' '.join(result)
       
       return cleaned_row
   
   # หาแถวที่มีคำใดๆ ในรายการ
   rows_with_words = {}
   for idx, row in df.iterrows():
       has_word, found_word = has_any_word_in_row(row, word_list)
       if has_word:
           if found_word not in rows_with_words:
               rows_with_words[found_word] = idx
   
   if rows_with_words:
       # สร้าง copy ของ DataFrame
       df_result = df.copy()
       
       # แก้ไขแถวแรกของแต่ละคำ
       for word, first_idx in rows_with_words.items():
           df_result.loc[first_idx] = clean_row_multiple_words(df_result.loc[first_idx], [word])
       
       # หาแถวที่ต้องเก็บ (แถวแรกของแต่ละคำ + แถวที่ไม่มีคำใดๆ)
       keep_indices = set(rows_with_words.values())
       
       for idx, row in df.iterrows():
           has_word, _ = has_any_word_in_row(row, word_list)
           if not has_word:
               keep_indices.add(idx)
       
       return df_result.loc[sorted(keep_indices)]
   else:
       return df  # ถ้าไม่มีคำใดๆ ในรายการเลย

# ตัวอย่างการใช้งาน
sample_data = {
   'col1': ['กรดน้ำส้ม ดาน อินทรีย์', 'สารเคมี', 'เอทานอล ตัวทำละลาย', 'กรด ดาน', 'ดาน เคมี', 'อินทรีย์ เคมี'],
   'col2': ['เคมี อนินทรีย์', 'ดาน ตัวทำละลาย ดาน', 'อินทรีย์', 'สาร ดาน อนินทรีย์', 'น้ำ', 'เคมี เคมี'],
   'col3': ['ตัวทำละลาย', 'อนินทรีย์ ดาน', 'เคมี ดาน ดาน', 'สาร', 'ตัวทำละลาย ดาน', 'อินทรีย์ อินทรีย์']
}

df = pd.DataFrame(sample_data)
print("ข้อมูลเดิม:")
print(df)

# ใช้งานกับหลายคำพร้อมกัน
words_to_clean = ['ดาน', 'เคมี', 'อินทรีย์']
df_cleaned = clean_multiple_words_anywhere(df, words_to_clean)
print(f"\nหลังทำความสะอาดคำ {words_to_clean}:")
print(df_cleaned)

ข้อมูลเดิม:
                     col1                col2               col3
0  กรดน้ำส้ม ดาน อินทรีย์      เคมี อนินทรีย์         ตัวทำละลาย
1                 สารเคมี  ดาน ตัวทำละลาย ดาน      อนินทรีย์ ดาน
2      เอทานอล ตัวทำละลาย            อินทรีย์       เคมี ดาน ดาน
3                 กรด ดาน   สาร ดาน อนินทรีย์                สาร
4                ดาน เคมี                 น้ำ     ตัวทำละลาย ดาน
5           อินทรีย์ เคมี           เคมี เคมี  อินทรีย์ อินทรีย์

หลังทำความสะอาดคำ ['ดาน', 'เคมี', 'อินทรีย์']:
                     col1            col2               col3
0  กรดน้ำส้ม ดาน อินทรีย์  เคมี อนินทรีย์         ตัวทำละลาย
2      เอทานอล ตัวทำละลาย        อินทรีย์       เคมี ดาน ดาน
5           อินทรีย์ เคมี                  อินทรีย์ อินทรีย์

In [57]:
df_cleaned_ = clean_multiple_words_anywhere(new, test)

In [59]:
df_cleaned_.to_csv('book_test.csv',encoding='utf-8-sig',index=False)